PROFILES_ACTIVE: local

DB_HOST: 100.96.1.4
DB_PORT: 1521
DB_SERVICE: xe
DB_USERNAME: business_core
DB_PASSWORD: Business@123

HSM_URL: http://localhost:8086/hsm
HSM_SIGN_ENDPOINT: /sign
HSM_VERIFY_ENDPOINT: /verify?keyName=app

SECRET_KEY: 159357